kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "incident-service-build" 
spec:
  runPolicy: "Serial" 
  strategy: 
    sourceStrategy:
      from:
        kind: "ImageStreamTag"
        name: "python:3.6"
        namespace: openshift
  output: 
    to:
      kind: "ImageStreamTag"
      name: "incident-service-rd:latest"
  source:
    git: 
      uri: "https://github.com/martinrm77/workshop-hackathon.git"
      ref: "master"
    contextDir: "solutions/python"
  triggers:
    - type: GitHub
      github:
        secretReference:
          name: "github-push-webhook"